
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: Kotosearch_development

test:
  <<: *default
  database: Kotosearch_test

production:
  <<: *default
  database: Kotosearch_production
  password:
  socket: /var/lib/mysql/mysql.sock
